package com.twistlet.soberspider.model.type;

public enum ColumnType {
	COLUMN_TYPE_, COLUMN_TYPE_LONGVARBINARY, COLUMN_TYPE_VARCHAR, COLUMN_TYPE_CHAR, COLUMN_TYPE_DATE, COLUMN_TYPE_DATETIME, COLUMN_TYPE_DECIMAL, COLUMN_TYPE_INTEGER, COLUMN_TYPE_TIMESTAMP, COLUMN_TYPE_BOOLEAN
}
